{
 "title": "Ballerina Metrics",
 "description": "Monitor Ballerina HTTP/HTTPs Services, HTTP Clients and SQL Clients",
 "tags": [
  "ballerina",
  "http",
  "sql"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(requests_total_value,instance)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(requests_total_value,service)"
   },
   {
    "name": "resource",
    "label": "resource",
    "query": "label_values(requests_total_value,resource)"
   },
   {
    "name": "protocol",
    "label": "protocol",
    "query": "label_values(requests_total_value,protocol)"
   },
   {
    "name": "http_method",
    "label": "http-method",
    "query": "label_values(requests_total_value,http_method)"
   },
   {
    "name": "http_url",
    "label": "http-url",
    "query": "label_values(requests_total_value,http_url)"
   },
   {
    "name": "http_client_action",
    "label": "http-client-action",
    "query": "label_values(requests_total_value,action)"
   },
   {
    "name": "db_action",
    "label": "db-action",
    "query": "label_values(requests_total_value{connector_name=\"ballerina/java_jdbc/Client\"},action)"
   },
   {
    "name": "connector_name",
    "label": "connector-name",
    "query": "label_values(requests_total_value,connector_name)"
   },
   {
    "name": "http_status_code_group",
    "label": "http-status-code-group",
    "query": "label_values(requests_total_value,http_status_code_group)"
   },
   { "name": "peer_address", "label": "peer-address", "query": "label_values(peer_address)" }
  ]
 },
 "panels": [
  {
   "title": "Ballerina Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Ballerina HTTP Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Avg Requests / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "\nsum(max_over_time(requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",service=~\"$service\",resource=~\"$resource\",connector_name=\"http\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",service=~\"$service\",resource=~\"$resource\",connector_name=\"http\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors /  min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(max_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m]))) OR vector(0))+((sum(max_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m]))) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Inprogress Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(inprogress_requests_value{instance=~\"$instance\",service=~\"$service\",resource=~\"$resource\",connector_name=\"http\"})"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(max_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])\n-\n  min_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])) OR vector(0))\n+\n(sum(max_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m]) \n-    min_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m])) OR vector(0)))\n*100\n/\nsum(max_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",connector_name=\"ballerina/http/Caller\"}[1m]))\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "sum without (http_status_code)(rate(requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",service=~\"$service\",resource=~\"$resource\",connector_name=\"http\"}[1m]))",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "response_time_seconds{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",service=~\"$service\",resource=~\"$resource\",connector_name=\"http\"}",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}, Quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "rate(requests_total_value{instance=~\"$instance\", action=~\"respond\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"1xx\"}[1m])",
     "legendFormat": "1xx Informational responses - Instance: {{instance}}"
    },
    {
     "expr": "rate(requests_total_value{instance=~\"$instance\", action=~\"respond\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"2xx\"}[1m])",
     "legendFormat": "2xx Successful responses - Instance: {{instance}}"
    },
    {
     "expr": "rate(requests_total_value{instance=~\"$instance\", action=~\"respond\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"3xx\"}[1m])",
     "legendFormat": "3xx Redirections - Instance: {{instance}}"
    },
    {
     "expr": "rate(requests_total_value{instance=~\"$instance\", action=~\"respond\",connector_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])",
     "legendFormat": "4xx Client errors - Instance: {{instance}}"
    },
    {
     "expr": "rate(requests_total_value{instance=~\"$instance\", action=~\"respond\",connector_name=\"ballerina/http/Caller\",http_status_code=\"5xx\"}[1m])",
     "legendFormat": "5xx Server errors - Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,requests_total_value{connector_name=\"http\"})",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}"
    }
   ]
  },
  { "title": "Ballerina HTTP Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Requests / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( max_over_time(requests_total_value{connector_name=\"ballerina/http/HttpClient\",instance=~\"$instance\", peer_address=~\"$peer_address\", action=~\"$http_client_action\"}[1m]) - min_over_time(requests_total_value{connector_name=\"ballerina/http/HttpClient\",instance=~\"$instance\", peer_address=~\"$peer_address\", action=~\"$http_client_action\"}[1m]) ) "
    }
   ]
  },
  {
   "title": "Errors /  min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum( max_over_time(requests_total_value{ instance=~\"$instance\", action=~\"$http_client_action\",http_status_code_group=\"4xx\",connector_name=\"ballerina/http/HttpClient\"}[1m]) - min_over_time(requests_total_value{ instance=~\"$instance\", action=~\"$http_client_action\",http_status_code_group=\"4xx\",connector_name=\"ballerina/http/HttpClient\"}[1m]))) OR vector(0)) + ((sum(max_over_time(requests_total_value{ instance=~\"$instance\", action=~\"$http_client_action\",http_status_code_group=\"5xx\",connector_name=\"ballerina/http/HttpClient\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\",http_status_code_group=\"5xx\",connector_name=\"ballerina/http/HttpClient\"}[1m]))) OR vector(0))"
    }
   ]
  },
  {
   "title": "Inprogress Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(inprogress_requests_value{connector_name=\"ballerina/http/HttpClient\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum( max_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/HttpClient\",http_status_code_group=\"4xx\"}[1m]) - min_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/HttpClient\",http_status_code_group=\"4xx\"}[1m])) OR vector(0)) + ((sum(max_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/HttpClient\",http_status_code_group=\"5xx\"}[1m]) - min_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/HttpClient\",http_status_code_group=\"5xx\"}[1m])) OR  vector(0) )))*100 / sum( max_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/HttpClient\"}[1m]) - min_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/HttpClient\"}[1m]))\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "sum without (http_status_code) (rate(requests_total_value{instance=~\"$instance\",action=~\"$http_client_action\",http_method=~\"$http_method\",http_url=~\"$http_url\",peer_address=~\"$peer_address\",connector_name=\"ballerina/http/HttpClient\"}[1m]))",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Method: {{http_method}}, Peer Address: {{peer_address}}, URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "sum without(http_status_code) ({__name__=~\"response_time_seconds_value\", instance=~\"$instance\",action=~\"$http_client_action\",http_method=~\"$http_method\",http_url=~\"$http_url\",connector_name=\"ballerina/http/Client\"})",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Method: {{http_method}}, Peer Address: {{peer_address}}, URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/Client\",http_status_code=\"1xx\"}[1m])",
     "legendFormat": "1xx Informational responses - Instance: {{instance}}, Action: {{action}}"
    },
    {
     "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/Client\",http_status_code_group=\"2xx\"}[1m])",
     "legendFormat": "2xx Successful responses - Instance: {{instance}}, Action: {{action}}"
    },
    {
     "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/Client\",http_status_code_group=\"3xx\"}[1m])",
     "legendFormat": "3xx Redirections - Instance: {{instance}}, Action: {{action}}"
    },
    {
     "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/Client\",http_status_code_group=\"4xx\"}[1m])",
     "legendFormat": "4xx Client errors - Instance: {{instance}}, Action: {{action}}"
    },
    {
     "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\",connector_name=\"ballerina/http/Client\",http_status_code_group=\"5xx\"}[1m])",
     "legendFormat": "5xx Server errors - Instance: {{instance}}, Action: {{action}}"
    }
   ]
  },
  {
   "title": "Top 5 remote services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,requests_total_value{connector_name=\"ballerina/http/Client\"})",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Method: {{http_method}}, Peer Address: {{peer_address}}, URL: {{http_url}}"
    }
   ]
  },
  { "title": "Ballerina SQL Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Executions / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors /  min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (max_over_time(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\",error=\"true\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\",error=\"true\"}[1m])) OR  vector(0)"
    }
   ]
  },
  {
   "title": "Inprogress Statements",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(inprogress_requests_value{action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\"})"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (max_over_time(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\",error=\"true\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\",error=\"true\"}[1m]))*100/sum(max_over_time(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\"}[1m]))"
    }
   ]
  },
  {
   "title": "Ballerina SQL Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "ops", "label": "Statements / sec" }
   ],
   "targets": [
    {
     "expr": "rate(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\"}[1m])",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Peer Address: {{peer_address}}, DB Instance: {{db_instance}}, DB Statement: {{db_statement}}"
    }
   ]
  },
  {
   "title": "Ballerina SQL Response Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "response_time_seconds{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\"}",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Quantile: {{quantile}}, Peer Address: {{peer_address}}, DB Instance: {{db_instance}}, DB Statement: {{db_statement}}"
    }
   ]
  },
  {
   "title": "Ballerina SQL Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ops", "label": "Statements / sec" }
   ],
   "targets": [
    {
     "expr": "rate(requests_total_value{instance=~\"$instance\",action=~\"$db_action\",connector_name=\"ballerina/java_jdbc/Client\",error=\"true\"}[1m])",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Peer Address: {{peer_address}}, DB Instance: {{db_instance}}, DB Statement: {{db_statement}}"
    }
   ]
  },
  {
   "title": "Top 5 SQL actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,requests_total_value{connector_name=\"ballerina/java_jdbc/Client\"})",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Peer Address: {{peer_address}}, DB Instance: {{db_instance}}, DB Statement: {{db_statement}}"
    }
   ]
  }
 ]
}