{
 "title": "Ballerina System Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Service Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ballerina Scheduler Count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Numbers" }
   ],
   "targets": [
    {
     "expr": "ballerina_scheduler_waiting_for_response_worker_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}--ballerina_scheduler_waiting_for_response_worker_count"
    },
    {
     "expr": "ballerina_scheduler_waiting_for_lock_worker_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}--ballerina_scheduler_waiting_for_lock_worker_count"
    },
    {
     "expr": "ballerina_scheduler_ready_worker_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}--ballerina_scheduler_ready_worker_count"
    },
    {
     "expr": "ballerina_scheduler_running_worker_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}--ballerina_scheduler_running_worker_count"
    },
    {
     "expr": "ballerina_scheduler_paused_worker_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}--ballerina_scheduler_paused_worker_count"
    },
    {
     "expr": "ballerina_scheduler_excepted_worker_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}--ballerina_scheduler_excepted_worker_count"
    }
   ]
  },
  {
   "title": "Average Ballerina Scheduler Count by Instance",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Numbers" }
   ],
   "targets": [
    {
     "expr": "avg(ballerina_scheduler_waiting_for_response_worker_count)by(instance)",
     "legendFormat": "{{instance}}--ballerina_scheduler_waiting_for_response_worker_count"
    },
    {
     "expr": "avg(ballerina_scheduler_waiting_for_lock_worker_count)by(instance)",
     "legendFormat": "{{instance}}--ballerina_scheduler_waiting_for_lock_worker_count"
    },
    {
     "expr": "avg(ballerina_scheduler_ready_worker_count)by(instance)",
     "legendFormat": "{{instance}}--ballerina_scheduler_ready_worker_count"
    },
    {
     "expr": "avg(ballerina_scheduler_running_worker_count)by(instance)",
     "legendFormat": "{{instance}}--ballerina_scheduler_running_worker_count"
    },
    {
     "expr": "avg(ballerina_scheduler_paused_worker_count)by(instance)",
     "legendFormat": "{{instance}}--ballerina_scheduler_paused_worker_count"
    },
    {
     "expr": "avg(ballerina_scheduler_excepted_worker_count)by(instance)",
     "legendFormat": "{{instance}}--ballerina_scheduler_excepted_worker_count"
    }
   ]
  }
 ]
}